# Generated by Django 3.1 on 2020-09-01 10:10

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominode_validation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationreport',
            name='report',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
