# Generated by Django 3.1 on 2020-09-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominode_validation', '0003_auto_20200901_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominoderesource',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
