@startuml
title
    = DomiNode workflow activity diagram

end title
|Metadata custodian|
|Dataset custodian|
start
:A1 - Acquire dataset;
if (Dataset is vector?) then (Yes)
    :A2.1 - Upload dataset to
    PostGIS staging schema;
else (No)
    :A2.2 - Upload dataset to
    staging filesystem;
endif
repeat :A3 - Prepare dataset for publication;
    :A4 - Validate dataset;
repeat while (Dataset valid?) is (No)
-> Yes;
if (Dataset is vector?) then (Yes)
    :A5.1 - Move dataset to
    production schema;
else (No)
    :A5.2 - Move dataset to
    production filesystem;
endif
:A6 - Publish dataset to
INTERNAL_GROUP via GeoServer;
|Style custodian|
repeat :A7 - Create/tweak QGIS style;
    :A8 - Validate QGIS style;
repeat while (QGIS style valid?) is (No)
-> Yes;
if (Dataset is vector?) then (Yes)
   : A9.1 - Save QGIS style in PostGIS DB;
else (No)
   : A9.2 - Save QGIS style in filesystem;
endif
repeat :A10 - Create SLD style;
    :A11 - Validate SLD style;
repeat while (SLD style valid?) is (No)
-> Yes;
: A12 - Save SLD style in GeoServer DB;
|Dataset custodian|
:A13 - Publish dataset to
INTERNAL_GROUP via GeoNode;
|Metadata custodian|
repeat :A14 - Create/tweak metadata with GeoNode;
    :A15 - Validate metadata;
repeat while (Metadata valid?) is (No)
-> Yes;
|Dataset custodian|
:A16 - Publish dataset via GeoNode to WORLD;
if (Data policy allows free access?) then (Yes)
    :A17 - Publish dataset via GeoServer to WORLD;
else (No)
    :A18 - Publish dataset via GeoServer to PAYING_CUSTOMERS;
endif
end
@enduml