# Generated by Django 2.2.15 on 2020-09-22 04:52

from django.db import migrations
from django.contrib.auth.models import Permission


def create_permission(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    db_alias = schema_editor.connection.alias
    content_type = ContentType.objects.using(db_alias).create(
        app_label='cors',
        model='cors_permission'
    )
    Permission.objects.using(db_alias).create(
        codename='download_observation',
        name='Download observation',
        content_type=content_type
    )


def delete_permission(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    db_alias = schema_editor.connection.alias
    Permission.objects.using(db_alias).filter(
        codename='download_observation',
        name='Download observation'
    ).delete()
    ContentType.objects.using(db_alias).filter(
        app_label='cors',
        model='cors_permission'
    ).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.RunPython(create_permission, delete_permission),
    ]
